//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyTitle("TvUndergroundDownloaderLib.EmbendedWebServer")]
[assembly: System.Reflection.AssemblyDescription("Tv Underground Downloader")]
[assembly: System.Reflection.AssemblyProduct("Tv Underground Downloader")]
[assembly: System.Reflection.AssemblyCopyright("Copyright(C) 2017 linefinc[at]users.sourceforge.net")]
[assembly: System.Reflection.AssemblyInformationalVersion("0.9.0 50862a1 [2017-10-15]")]
[assembly: System.Runtime.InteropServices.ComVisible(false)]
[assembly: System.CLSCompliant(true)]
[assembly: System.Reflection.AssemblyVersion("0.9.0")]
[assembly: System.Reflection.AssemblyFileVersion("0.9.0")]


