//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyVersion("0.5.6")]
[assembly: System.Reflection.AssemblyFileVersion("0.5.6")]
[assembly: System.Reflection.AssemblyInformationalVersion("0.5.6-3eeb15f [2015-07-04]")]
[assembly: System.Reflection.AssemblyTitle("TvUnderground Downloader")]
[assembly: System.Reflection.AssemblyProduct("TvUnderground Downloader")]


