//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyVersion("0.5.6")]
[assembly: System.Reflection.AssemblyInformationalVersion("0.5.6-6f000de-2015-06-20 15:25:11")]
[assembly: System.Reflection.AssemblyTitle("TvUnderground Downloader")]


