//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyVersion("0.6.2")]
[assembly: System.Reflection.AssemblyFileVersion("0.6.2")]
[assembly: System.Reflection.AssemblyInformationalVersion("0.6.2 63a0c27 [2016-10-31]")]
[assembly: System.Reflection.AssemblyTitle("TvUndergroundDownloader")]
[assembly: System.Reflection.AssemblyProduct("TvUndergroundDownloader")]


