//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyTitle("TvUndergroundDownloaderLib")]
[assembly: System.Reflection.AssemblyDescription("Tv Underground Downloader")]
[assembly: System.Reflection.AssemblyProduct("Tv Underground Downloader")]
[assembly: System.Reflection.AssemblyCopyright("Copyright(C) 2020 linefinc[at]users.sourceforge.net")]
[assembly: System.Reflection.AssemblyInformationalVersion("0.9.7 def14c0 [2020-01-25]")]
[assembly: System.Runtime.InteropServices.ComVisible(false)]
[assembly: System.CLSCompliant(true)]
[assembly: System.Reflection.AssemblyVersion("0.9.7")]
[assembly: System.Reflection.AssemblyFileVersion("0.9.7")]


