//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyDescription("Tv Underground Downloader")]
[assembly: System.CLSCompliant(true)]
[assembly: System.Runtime.InteropServices.ComVisible(false)]
[assembly: System.Reflection.AssemblyInformationalVersion("0.9.8 42fc32c [2021-04-20]")]
[assembly: System.Reflection.AssemblyProduct("Tv Underground Downloader")]
[assembly: System.Reflection.AssemblyCopyright("Copyright(C) 2021 linefinc[at]users.sourceforge.net")]
[assembly: System.Reflection.AssemblyFileVersion("0.9.8")]
[assembly: System.Reflection.AssemblyVersion("0.9.8")]
[assembly: System.Reflection.AssemblyTitle("TvUndergroundDownloader")]


