//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyVersion("0.9.0")]
[assembly: System.Reflection.AssemblyFileVersion("0.9.0")]
[assembly: System.Reflection.AssemblyInformationalVersion("0.9.0 46615d2 [2017-10-14]")]
[assembly: System.Reflection.AssemblyTitle("TvUndergroundDownloader")]
[assembly: System.Reflection.AssemblyProduct("TvUndergroundDownloader")]
[assembly: System.Reflection.AssemblyCopyright("Copyright(C) 2017 linefinc[at]users.sourceforge.net")]


